Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE contacts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    CONSTRAINT "PK_contacts" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231028212612_InitialCreate', '7.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE contacts ALTER COLUMN last_name DROP NOT NULL;

ALTER TABLE contacts ALTER COLUMN email DROP NOT NULL;

ALTER TABLE contacts ADD created_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE contacts ADD updated_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231031130606_AddedCreatedAndUpdatedAttributes', '7.0.13');

COMMIT;


